import { GoogleGenAI, GenerateContentResponse } from "@google/genai";

const getAI = () => {
  const apiKey = import.meta.env.VITE_GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error("GEMINI_API_KEY is not configured");
  }
  return new GoogleGenAI({ apiKey });
};

export type RestorationTask = 
  | "colorize" 
  | "restore" 
  | "upscale" 
  | "outpaint" 
  | "remove_bg"
  | "full_pro";

export async function processImage(
  base64Image: string, 
  task: RestorationTask,
  customPrompt?: string
): Promise<string> {
  const ai = getAI();
 const model = "gemini-1.5-flash";
  let prompt = "";
  switch (task) {
    case "full_pro":
      prompt = "Perform a complete professional restoration on this photo. 1. Colorize the image realistically if it is black and white. 2. Remove all scratches, cracks, noise, and physical defects. 3. Upscale the resolution by 2x while maintaining the original aspect ratio. 4. Sharpen faces and enhance all details. 5. Expand the background and complete the portrait (add arms, shoulders, and chest) if necessary to create a professional studio look. The final result should be a high-quality, modern, and clean photograph.";
      break;
    case "colorize":
      prompt = "Colorize this black and white photo realistically. Preserve all details and textures.";
      break;
    case "restore":
      prompt = "Restore this old photo. Remove cracks, scratches, noise, and physical defects. Sharpen faces and enhance overall clarity while maintaining the original look.";
      break;
    case "upscale":
      prompt = "Upscale this image to high resolution. Enhance details, remove compression artifacts, and sharpen edges without changing the aspect ratio.";
      break;
    case "outpaint":
      prompt = "Expand this photo. Remove the background and replace it with a clean, professional studio background. Add missing body parts like arms, shoulders, and chest to create a complete portrait. Ensure the lighting and style are consistent.";
      break;
    case "remove_bg":
      prompt = "Remove the background from this image and make it completely transparent. Keep only the subject with clean, sharp edges. Output as a PNG with transparency.";
      break;
    default:
      prompt = customPrompt || "Enhance this image.";
  }

  const response = await ai.models.generateContent({
    model,
    contents: {
      parts: [
        {
          inlineData: {
            data: base64Image.split(",")[1] || base64Image,
            mimeType: "image/png",
          },
        },
        { text: prompt },
      ],
    },
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
    }
  }

  throw new Error("No image was generated by the AI.");
}
